spring:
  application:
    name: accounts
build:
  version: "2.0"

accounts:    
  message: "{cipher}26059a0c6f32d4ae9b5ee01bd36bca339ebfff5dc0ac31b03dcec8be1b833bc09f905f82ce99bfdb29e4d33050a65f4a"
  contactDetails:
    email: "kalaiqa-team@gmail.com"
    address: "1013 East Street, Cross Road, San-fransico"
  onCallSupport:
    - 04366262506
    - 04366296103           
rabbitmq:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"        
        
