spring:
  config:
    activate:
      on-profile: "qa"
  
  
loans:    
  message: "Kindly contact qa-team"
  contactDetails:
    email: "kalaiqa-team@gmail.com"
    address: "1013 East Street, Cross Road, San-fransico - R-MQ"
  onCallSupport:
    - 04366262506
    - 04366296103  
    
build:
  version: "2.0"         
rabbitmq:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"        
          
