spring:
  application:
    name: cards
  
cards:    
  message: "Kindly contact qa-team"
  contactDetails:
    email: "kalaiqa-team@gmail.com"
    address: "1013 East Street, Cross Road, San-fransico - OLD"
  onCallSupport:
    - 04366262506
    - 04366296103  
       
  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"        
          
build:
  version: "2.0"  
